name: Auto backup GitHub Wiki to Code
author: Naoya Niwa
description: This action automatically backs up the contents of the GitHub Wiki to a specified branch.
branding:
  icon: github
  color: white

inputs:
  target_branch:
    description: 
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TARGET_BRANCH: ${{ inputs.target_branch }}