name: Auto backup GitHub Wiki to Code
author: Naoya Niwa
description: This action automatically backs up the contents of the GitHub Wiki to a specified branch.
branding:
  icon: refresh-cw
  color: white

inputs:
  target_branch:
    description: 
    required: true
  github_token:
    description:
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    TARGET_BRANCH: ${{ inputs.target_branch }}
