name: Wiki update

on:
  gollum

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: copy
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.wiki.git wiki
          cd wiki
          git remote add repo https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push repo master:wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}